set SERVEROUTPUT ON
CREATE OR REPLACE TRIGGER trig 
BEFORE UPDATE of job_id on temp_employees
for EACH row
DECLARE
new_high_sal NUMBER;
old_high_sal NUMBER;
job_year NUMBER;
new_dept employees.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT max(SALARY) into old_high_sal
    FROM EMPLOYEES
    WHERE JOB_ID=:OLD.job_id;
    SELECT max(SALARY) into new_high_sal
    FROM EMPLOYEES
    WHERE JOB_ID=:NEW.job_id;

    job_year:= MONTHS_BETWEEN(SYSDATE,:NEW.hire_date) /12;

    if old_high_sal< new_high_sal THEN
        NULL;
    ELSIF job_year <5 THEN
        NULL;

    ELSE RAISE_APPLICATION_ERROR(-20001,'Rank mismatch');
    end if;

    SELECT DEPARTMENT_ID into new_dept
    FROM DEPARTMENT_JOB_MAP_TABLE
    WHERE JOB_ID=:NEW.job_id;

    :new.department_id:=new_dept;

    INSERT INTO LOG_TEMP_EMPLOYEES_UPDATE_JID (EMPLOYEE_ID, OLD_JOB_ID, NEW_JOB_ID, UPDATE_DATE)
    VALUES (:NEW.employee_id, :OLD.job_id, :NEW.job_id, SYSDATE);

END;
/

CREATE TABLE LOG_TEMP_EMPLOYEES_UPDATE_JID (
    EMPLOYEE_ID NUMBER,
    OLD_JOB_ID VARCHAR2(20),
    NEW_JOB_ID VARCHAR2(20),
    UPDATE_DATE DATE
); 

--UPDATE JOB_ID
UPDATE TEMP_EMPLOYEES
SET JOB_ID = 'MK_MAN'
WHERE EMPLOYEE_ID = 198;

SELECT * FROM LOG_TEMP_EMPLOYEES_UPDATE_JID;

--UPDATE JOB_ID
UPDATE TEMP_EMPLOYEES
SET JOB_ID = 'AD_VP'
WHERE EMPLOYEE_ID = 200;

--UPDATE JOB_ID
UPDATE TEMP_EMPLOYEES
SET JOB_ID = 'AD_ASST'
WHERE EMPLOYEE_ID = 101;

--UPDATE JOB_ID
UPDATE TEMP_EMPLOYEES
SET JOB_ID = 'SA_REP'
WHERE EMPLOYEE_ID = 178;