SELECT * 
FROM EMPLOYEES e 
JOIN JOBS j ON e.JOB_ID=j.JOB_ID
WHERE j.MIN_SALARY>10000 OR 
e.DEPARTMENT_ID IN (
    SELECT EMPLOYEES.DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY EMPLOYEES.DEPARTMENT_ID
    HAVING COUNT(*)>5
)

MINUS 
SELECT * 
FROM EMPLOYEES e 
JOIN JOBS j ON e.JOB_ID=j.JOB_ID
WHERE j.MIN_SALARY>10000 AND
e.DEPARTMENT_ID IN (
    SELECT EMPLOYEES.DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY EMPLOYEES.DEPARTMENT_ID
    HAVING COUNT(*)>5
); 