-- SELECT SUBSTR(PHONE_NUMBER,1,INSTR(PHONE_NUMBER,'.')-1) as country_code, COUNT(*) emp_count
-- FROM EMPLOYEES
-- WHERE HIRE_DATE >'01-JAN-2005'
-- GROUP BY SUBSTR(PHONE_NUMBER,1,INSTR(PHONE_NUMBER,'.')-1)

-- SELECT EMPLOYEE_ID,SALARY, ABS(ROUND(SALARY/1000)*1000-SALARY) as salary_diff
-- FROM EMPLOYEES

CREATE TABLE EMP_TRAINING (
     TRAINING_ID NUMBER,
     EMPLOYEE_ID NUMBER,
     TRAINING_NAME VARCHAR2(50) NOT NULL,
     REG_DATE DATE DEFAULT SYSDATE,

     CONSTRAINT TRAINING_PK PRIMARY KEY (TRAINING_ID),
     CONSTRAINT EMP_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMP_TRAINING 
VALUES (1,101,'Mithun', '01-JAN-2005') ;


-- SELECT DEPARTMENT_ID, TO_CHAR(SUM(SALARY)*12, '99,999,999') as ann_pay
-- FROM EMPLOYEES
-- GROUP BY DEPARTMENT_ID
-- HAVING COUNT(*)>2 AND MIN(SALARY)>=2500


-- SELECT EMPLOYEE_ID, UPPER(SUBSTR(FIRST_NAME,1,2)) || LENGTH(LAST_NAME) || SUBSTR(PHONE_NUMBER,-1) as security_code
-- FROM EMPLOYEES
-- WHERE LENGTH(FIRST_NAME)> LENGTH(LAST_NAME)
-- ORDER BY LENGTH(security_code) DESC