-- SELECT COUNTRY_ID, COUNT(CITY) c_count, COUNT(STATE_PROVINCE) s_count
-- FROM LOCATIONS
-- GROUP BY COUNTRY_ID
-- HAVING COUNT(CITY)>=2 AND COUNT(STATE_PROVINCE)!=0
-- ORDER BY COUNTRY_ID ASC

-- There is a more accurate solution that involves join 
-- SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
-- FROM JOB_HISTORY 
-- WHERE END_DATE-START_DATE<=600 
-- GROUP BY DEPARTMENT_ID 
-- HAVING COUNT(EMPLOYEE_ID)<=1 

-- SELECT DEPARTMENT_ID, MIN(HIRE_DATE), MAX(HIRE_DATE), AVG(SALARY)
-- FROM EMPLOYEES 
-- WHERE DEPARTMENT_ID IS NOT NULL
-- GROUP BY DEPARTMENT_ID 
-- ORDER BY (MAX(HIRE_DATE)-MIN(HIRE_DATE)) ASC, AVG(SALARY) DESC

-- SELECT FIRST_NAME || ' ' || LAST_NAME AS full_name,
--        SALARY * 12 AS annual_salary,
--        SALARY AS current_monthly_salary,
--        COMMISSION_PCT,
--        ((SALARY * 12) + ((SALARY * 12) * NVL(COMMISSION_PCT, -0.05) / 100)) / 12 AS next_year_monthly_salary
-- FROM EMPLOYEES;


SELECT MANAGER_ID, 
       COUNT(EMPLOYEE_ID) AS emp_count, 
       AVG(SALARY) AS avg_salary
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
  -- Alternative Method: Convert Date to String
  AND TO_CHAR(HIRE_DATE, 'MM') IN ('03', '09', '12')
GROUP BY MANAGER_ID
HAVING AVG(SALARY) = TRUNC(AVG(SALARY))
ORDER BY emp_count ASC, avg_salary DESC;